---
title: "Color y recompensas"
author: "Marcial"
date: "01/09/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
1. Install and load packages

```{r, echo = F}
#devtools::install_github("jinyizju/V.PhyloMaker")
library(V.PhyloMaker)


```


3. Frequency matrix.

```{r, echo = F}
mydata <- read.csv("mydata4.csv", sep = ";", header=TRUE, stringsAsFactors=FALSE, fileEncoding="latin1")
mydata
```



3. Create your tree and plot

```{r, echo = F}

genera<-sapply(strsplit(mydata[,2]," "),function(x) x[1])

data <- data.frame(species = mydata[,2], genus = genera, family = mydata[,1])
my.phylo.maker <- phylo.maker(data, tree = GBOTB.extended, nodes = nodes.info.1, output.sp.list = TRUE, output.tree = FALSE, scenarios = c("S1","S2","S3"), r = 1)

plot(my.phylo.maker$scenario.3, cex = 0.6)

write.tree(my.phylo.maker$scenario.3, file = "mytree.tree")



```




```{r, echo = F}
library(caper)

mytree2 <- read.tree(file="mytree.tree")

class(mytree2)
plot(mytree2)
mydata$X5.NPOL <- as.numeric(mydata$X5.NPOL)
color <- comparative.data(mytree2, mydata, X2.Especies2, vcv=TRUE, vcv.dim=2, na.omit=F, 
	             force.root=FALSE, warn.dropped=T, scope=NULL)
plot(color$phy)
color$phy
color$dropped
dim(color$vcv)
    lambda.result1 <- pgls(X3.MSUG ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.result1)
    
    lambda.result2 <- pgls(X3.MSUG ~ X6.VPOL, color, lambda = "ML")
    summary(lambda.result2)
    
    lambda.result3 <- pgls(X3.MSUG ~ X9.SIZ, color, lambda = "ML")
    summary(lambda.result3)
    
    lambda.result4 <- pgls(X3.MSUG ~ X12.HUE, color, lambda = "ML")
    summary(lambda.result4)
    
    lambda.result5 <- pgls(X3.MSUG ~ X13.BRI, color, lambda = "ML")
    summary(lambda.result5)
    
    lambda.result6 <- pgls(X3.MSUG ~ X14.CHR, color, lambda = "ML")
    summary(lambda.result6)
    
    lambda.result7 <- pgls(X3.MSUG ~ X15.UV, color, lambda = "ML")
    summary(lambda.result7)
    
    lambda.result8 <- pgls(X3.MSUG ~ X16.GC, color, lambda = "ML")
    summary(lambda.result8)
    
    lambda.result9 <- pgls(X3.MSUG ~ X17.DIST, color, lambda = "ML")
    summary(lambda.result9)
        
    lambda.resulta0 <- pgls(X3.MSUG ~ Floral.display, color, lambda = "ML")
    summary(lambda.resulta0)
    
    lambda.resulta0.0 <- pgls(X3.MSUG ~ FdSize, color, lambda = "ML")
    summary(lambda.resulta0.0)
    
  
    
    
    lambda.resultb1 <- pgls(X4.CSUG ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.resultb1)
    
    lambda.resultb2 <- pgls(X4.CSUG ~ X6.VPOL, color, lambda = "ML")
    summary(lambda.resultb2)
    
    lambda.resultb3 <- pgls(X4.CSUG ~ X9.SIZ, color, lambda = "ML")
    summary(lambda.resultb3)

    lambda.resultb4 <- pgls(X4.CSUG ~ X12.HUE, color, lambda = "ML")
    summary(lambda.resultb4)
    
    lambda.resultb5 <- pgls(X4.CSUG ~ X13.BRI, color, lambda = "ML")
    summary(lambda.resultb5)
    
    lambda.resultb6 <- pgls(X4.CSUG ~ X14.CHR, color, lambda = "ML")
    summary(lambda.resultb6)
    
    lambda.resultb7 <- pgls(X4.CSUG ~ X15.UV, color, lambda = "ML")
    summary(lambda.resultb7)
    
    lambda.resultb8 <- pgls(X4.CSUG ~ X16.GC, color, lambda = "ML")
    summary(lambda.resultb8)
    
    lambda.resultb9 <- pgls(X4.CSUG ~ X17.DIST, color, lambda = "ML")
    summary(lambda.resultb9)

    lambda.resultb0 <- pgls(X4.CSUG ~ Floral.display, color, lambda = "ML")
    summary(lambda.resultb0)
    
    lambda.resultb0.0 <- pgls(X4.CSUG ~ FdSize, color, lambda = "ML")
    summary(lambda.resultb0.0)
    
    
    lambda.resultc1 <- pgls(X5.NPOL ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resultc1)
    
    lambda.resultc2 <- pgls(X5.NPOL ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resultc2)
    
    lambda.resultc3 <- pgls(X5.NPOL ~ X9.SIZ, color, lambda = "ML")
    summary(lambda.resultc3)
    
    lambda.resultc4 <- pgls(X5.NPOL ~ X12.HUE, color, lambda = "ML")
    summary(lambda.resultc4)
    
    lambda.resultc5 <- pgls(X5.NPOL ~ X13.BRI, color, lambda = "ML")
    summary(lambda.resultc5)
    
    lambda.resultc6 <- pgls(X5.NPOL ~ X14.CHR, color, lambda = "ML")
    summary(lambda.resultc6)
    
    lambda.resultc7 <- pgls(X5.NPOL ~ X15.UV, color, lambda = "ML")
    summary(lambda.resultc7)
    
    lambda.resultc8 <- pgls(X5.NPOL ~ X16.GC, color, lambda = "ML")
    summary(lambda.resultc8)
    
    lambda.resultc9 <- pgls(X5.NPOL ~ X17.DIST, color, lambda = "ML")
    summary(lambda.resultc9)
    
    lambda.resultc0 <- pgls(X5.NPOL ~ Floral.display, color, lambda = "ML")
    summary(lambda.resultc0)
    
    lambda.resultc0.0 <- pgls(X5.NPOL ~ FdSize, color, lambda = "ML")
    summary(lambda.resultc0.0)
    
    
    
    lambda.resultd1 <- pgls(X6.VPOL ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resultd1)
    
    lambda.resultd2 <- pgls(X6.VPOL ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resultd2)
    
    lambda.resultd3 <- pgls(X6.VPOL ~ X9.SIZ, color, lambda = "ML")
    summary(lambda.resultd3)
    
    lambda.resultd4 <- pgls(X6.VPOL ~ X12.HUE, color, lambda = "ML")
    summary(lambda.resultd4)
    
    lambda.resultd5 <- pgls(X6.VPOL ~ X13.BRI, color, lambda = "ML")
    summary(lambda.resultd5)
    
    lambda.resultd6 <- pgls(X6.VPOL ~ X14.CHR, color, lambda = "ML")
    summary(lambda.resultd6)
    
    lambda.resultd7 <- pgls(X6.VPOL ~ X15.UV, color, lambda = "ML")
    summary(lambda.resultd7)
    
    lambda.resultd8 <- pgls(X6.VPOL ~ X16.GC, color, lambda = "ML")
    summary(lambda.resultd8)
    
    lambda.resultd9 <- pgls(X6.VPOL ~ X17.DIST, color, lambda = "ML")
    summary(lambda.resultd9)

    lambda.resultd0 <- pgls(X6.VPOL ~ Floral.display, color, lambda = "ML")
    summary(lambda.resultd0)
    
    lambda.resultd0.0 <- pgls(X6.VPOL ~ FdSize, color, lambda = "ML")
    summary(lambda.resultd0.0)
    
    
    
    
    lambda.resulte1 <- pgls(X9.SIZ ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resulte1)
    
    lambda.resulte2 <- pgls(X9.SIZ ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resulte2)
    
    lambda.resulte3 <- pgls(X9.SIZ ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.resulte3)
    
    lambda.resulte4 <- pgls(X9.SIZ ~ X6.VPOL, color, lambda = "ML")
    summary(lambda.resulte4)
    
    lambda.resulte5 <- pgls(X9.SIZ ~ X12.HUE, color, lambda = "ML")
    summary(lambda.resulte5)
    
    lambda.resulte6 <- pgls(X9.SIZ ~ X13.BRI, color, lambda = "ML")
    summary(lambda.resulte6)
    
    lambda.resulte7 <- pgls(X9.SIZ ~ X14.CHR, color, lambda = "ML")
    summary(lambda.resulte7)
    
    lambda.resulte8 <- pgls(X9.SIZ ~ X15.UV, color, lambda = "ML")
    summary(lambda.resulte8)
    
    lambda.resulte9 <- pgls(X9.SIZ ~ X16.GC, color, lambda = "ML")
    summary(lambda.resulte9)
    
    lambda.resulte10 <- pgls(X9.SIZ ~ X17.DIST, color, lambda = "ML")
    summary(lambda.resulte10)
    
    lambda.resulte0 <- pgls(X9.SIZ ~ Floral.display, color, lambda = "ML")
    summary(lambda.resulte0)
    
    lambda.resulte0.0 <- pgls(X9.SIZ ~ FdSize, color, lambda = "ML")
    summary(lambda.resulte0.0)
    
    
    
    
    lambda.resultz1 <- pgls(Floral.display ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resultz1)
    
    lambda.resultz2 <- pgls(Floral.display ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resultz2)
    
    lambda.resultz3 <- pgls(Floral.display ~ X9.SIZ, color, lambda = "ML")
    summary(lambda.resultz3)
    
    lambda.resultz4 <- pgls(Floral.display ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.resultz4)
    
    lambda.resultz5 <- pgls(Floral.display ~ X6.VPOL, color, lambda = "ML")
    summary(lambda.resultz5)
    
    lambda.resultz6 <- pgls(Floral.display ~ X12.HUE, color, lambda = "ML")
    summary(lambda.resultz6)
    
    lambda.resultz7 <- pgls(Floral.display ~ X13.BRI, color, lambda = "ML")
    summary(lambda.resultz7)
    
    lambda.resultz8 <- pgls(Floral.display ~ X14.CHR, color, lambda = "ML")
    summary(lambda.resultz8)
    
    lambda.resultz9 <- pgls(Floral.display ~ X15.UV, color, lambda = "ML")
    summary(lambda.resultz9)
    
    lambda.resultz10 <- pgls(Floral.display ~ X16.GC, color, lambda = "ML")
    summary(lambda.resultz10)
    
    lambda.resultz11 <- pgls(Floral.display ~ X17.DIST, color, lambda = "ML")
    summary(lambda.resultz11)
    
    lambda.resultz0.0 <- pgls(Floral.display ~ FdSize, color, lambda = "ML")
    summary(lambda.resultz0.0)
    
    
    
    
    lambda.resulty1 <- pgls(FdSize ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resulty1)
    
    lambda.resulty2 <- pgls(FdSize ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resulty2)
    
    lambda.resulty3 <- pgls(FdSize ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.resulty3)
    
    lambda.resulty4 <- pgls(FdSize ~ X6.VPOL, color, lambda = "ML")
    summary(lambda.resulty4)
    
    lambda.resulty5 <- pgls(FdSize ~ X12.HUE, color, lambda = "ML")
    summary(lambda.resulty5)
    
    lambda.resulty6 <- pgls(FdSize ~ X13.BRI, color, lambda = "ML")
    summary(lambda.resulty6)
    
    lambda.resulty7 <- pgls(FdSize ~ X14.CHR, color, lambda = "ML")
    summary(lambda.resulty7)
    
    lambda.resulty8 <- pgls(FdSize ~ X15.UV, color, lambda = "ML")
    summary(lambda.resulty8)
    
    lambda.resulty9 <- pgls(FdSize ~ X16.GC, color, lambda = "ML")
    summary(lambda.resulty9)
    
    lambda.resulty10 <- pgls(FdSize ~ X17.DIST, color, lambda = "ML")
    summary(lambda.resulty10)
    
    lambda.resulty11 <- pgls(FdSize ~ X9.SIZ, color, lambda = "ML")
    summary(lambda.resulty11)
    
    lambda.resulty0 <- pgls(FdSize ~ Floral.display, color, lambda = "ML")
    summary(lambda.resulty0)
    
    
    
    
    
 lambda.resultf1 <- pgls(X12.HUE ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resultf1)
    lambda.resultf2 <- pgls(X12.HUE ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resultf2)
    lambda.resultf3 <- pgls(X12.HUE ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.resultf3)
    lambda.resultf4 <- pgls(X12.HUE ~ X6.VPOL, color, lambda = "ML")   
     summary(lambda.resultf4)
    lambda.resultf5 <- pgls(X12.HUE ~ X9.SIZ, color, lambda = "ML")   
     summary(lambda.resultf5)
    lambda.resultf0 <- pgls(X12.HUE ~ Floral.display, color, lambda = "ML")   
     summary(lambda.resultf0)
    lambda.resultf0.0 <- pgls(X12.HUE ~ FdSize, color, lambda = "ML")   
     summary(lambda.resultf0.0) 
     
     
 lambda.resultg1 <- pgls(X13.BRI ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resultg1)
    lambda.resultg2 <- pgls(X13.BRI ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resultg2)
    lambda.resultg3 <- pgls(X13.BRI ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.resultg3)
    lambda.resultg4 <- pgls(X13.BRI ~ X6.VPOL, color, lambda = "ML")   
     summary(lambda.resultg4)
    lambda.resultg5 <- pgls(X13.BRI ~ X9.SIZ, color, lambda = "ML")   
     summary(lambda.resultg5)
    lambda.resultg0 <- pgls(X13.BRI ~ Floral.display, color, lambda = "ML")   
     summary(lambda.resultf0)
    lambda.resultg0.0 <- pgls(X13.BRI ~ FdSize, color, lambda = "ML")   
     summary(lambda.resultf0.0) 
     
lambda.resulth1 <- pgls(X14.CHR ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resulth1)
    lambda.resulth2 <- pgls(X14.CHR ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resulth2)
    lambda.resulth3 <- pgls(X14.CHR ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.resulth3)
    lambda.resulth4 <- pgls(X14.CHR ~ X6.VPOL, color, lambda = "ML")   
     summary(lambda.resulth4)
    lambda.resulth5 <- pgls(X14.CHR ~ X9.SIZ, color, lambda = "ML")   
     summary(lambda.resulth5)
    lambda.resulth0 <- pgls(X14.CHR ~ Floral.display, color, lambda = "ML")   
     summary(lambda.resulth0)
    lambda.resulth0.0 <- pgls(X14.CHR ~ FdSize, color, lambda = "ML")   
     summary(lambda.resulth0.0) 

lambda.resulti1 <- pgls(X15.UV ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resulti1)
    lambda.resulti2 <- pgls(X15.UV ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resulti2)
    lambda.resulti3 <- pgls(X15.UV ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.resulti3)
    lambda.resulti4 <- pgls(X15.UV ~ X6.VPOL, color, lambda = "ML")   
     summary(lambda.resulti4)
    lambda.resulti5 <- pgls(X15.UV ~ X9.SIZ, color, lambda = "ML")   
     summary(lambda.resulti5)
       lambda.resulti0 <- pgls(X15.UV ~ Floral.display, color, lambda = "ML")   
     summary(lambda.resulti0)
    lambda.resulti0.0 <- pgls(X15.UV ~ FdSize, color, lambda = "ML")   
     summary(lambda.resulti0.0) 

lambda.resultj1 <- pgls(X16.GC ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resultj1)
    lambda.resultj2 <- pgls(X16.GC ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resultj2)
    lambda.resultj3 <- pgls(X16.GC ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.resultj3)
    lambda.resultj4 <- pgls(X16.GC ~ X6.VPOL, color, lambda = "ML")   
     summary(lambda.resultj4)
    lambda.resultj5 <- pgls(X16.GC ~ X9.SIZ, color, lambda = "ML")   
     summary(lambda.resultj5)
       lambda.resultj0 <- pgls(X16.GC ~ Floral.display, color, lambda = "ML")   
     summary(lambda.resultj0)
    lambda.resultj0.0 <- pgls(X16.GC ~ FdSize, color, lambda = "ML")   
     summary(lambda.resultj0.0) 
     
     
     

lambda.resultk1 <- pgls(X17.DIST ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resultk1)
    lambda.resultk2 <- pgls(X17.DIST ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resultk2)
    lambda.resultk3 <- pgls(X17.DIST ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.resultk3)
    lambda.resultk4 <- pgls(X17.DIST ~ X6.VPOL, color, lambda = "ML")   
     summary(lambda.resultk4)
    lambda.resultk5 <- pgls(X17.DIST ~ X9.SIZ, color, lambda = "ML")   
     summary(lambda.resultk5)
    lambda.resultk0 <- pgls(X17.DIST ~ Floral.display, color, lambda = "ML")   
     summary(lambda.resultk0)
    lambda.resultk0.0 <- pgls(X17.DIST ~ FdSize, color, lambda = "ML")   
     summary(lambda.resultk0.0) 

```



Phylogenetic signal

```{r, echo = F}

lambda.resultm1 <- pgls(X3.MSUG ~ 1, color, lambda = "ML")
    summary(lambda.resultm1)
lambda.resultm2 <- pgls(X4.CSUG ~ 1, color, lambda = "ML")
    summary(lambda.resultm2)
lambda.resultm3 <- pgls(X5.NPOL ~ 1, color, lambda = "ML")
    summary(lambda.resultm3)
lambda.resultm4 <- pgls(X6.VPOL ~ 1, color, lambda = "ML")
    summary(lambda.resultm4)
lambda.resultm5 <- pgls(X9.SIZ ~ 1, color, lambda = "ML")
    summary(lambda.resultm5)
lambda.resultm0 <- pgls(Floral.display ~ 1, color, lambda = "ML")
    summary(lambda.resultm0)
lambda.resultm0.0 <- pgls(FdSize ~ 1, color, lambda = "ML")
    summary(lambda.resultm0.0)
lambda.resultm6 <- pgls(X12.HUE ~ 1, color, lambda = "ML")
    summary(lambda.resultm6)
lambda.resultm7 <- pgls(X13.BRI ~ 1, color, lambda = "ML")
    summary(lambda.resultm7)
lambda.resultm8 <- pgls(X14.CHR ~ 1, color, lambda = "ML")
    summary(lambda.resultm8)
lambda.resultm9 <- pgls(X15.UV ~ 1, color, lambda = "ML")
    summary(lambda.resultm9)
lambda.resultm10 <- pgls(X16.GC ~ 1, color, lambda = "ML")
    summary(lambda.resultm10)
lambda.resultm11 <- pgls(X17.DIST ~ 1, color, lambda = "ML")
    summary(lambda.resultm11)
    
    


               
    
```

Plotting

```{r, echo = F}

#library(devtools)
#install_github("liamrevell/phytools")
library(phytools)

rownames(mydata) <- as.character(mydata$X2.Especies2)

colors<-colorRampPalette(colors=gray.colors(100, alpha = 1))(100) #blanco y negro

colors<-colorRampPalette(colors=heat.colors(100, alpha = 1))(100) #escala naranja

traits <- mydata[,c("X3.MSUG", "X4.CSUG", "X5.NPOL", "X6.VPOL", "X9.SIZ", "X12.HUE", "X13.BRI", "X14.CHR", "X15.UV", "X16.GC", "X17.DIST", "Floral.display")]
colnames(traits) <- c("Sugar Mass", "Sugar Conc.", "Pollen Num.", "Pollen Vol.", "Flow. Size", "Hue", "Brigthness", "Chroma", "UV Chroma", "Green C.", "Backgr. C.", "Floral display")

phylo.heatmap(mytree2,traits,ftype="i", fsize = c(0.35,0.5,0.5),colors=colors,standardize=T,lwd=1, pts=F, grid=F, legend = F, split=c(0.70,0.30))

#para que salga la leyenda legend=T



```

Cathegorical variables

```{r,  echo = F}

    lambda.resultg1 <- pgls(X9.SIZ ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg1)
    anova(lambda.resultg1)
    lambda.resultg0 <- pgls(Floral.display ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg0)
    lambda.resultg0.0 <- pgls(FdSize ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg0.0)
    
    lambda.resultg2 <- pgls(X5.NPOL ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg2)
    lambda.resultg3 <- pgls(X6.VPOL ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg3)
    lambda.resultg4 <- pgls(X12.HUE ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg4)
    lambda.resultg5 <- pgls(X13.BRI ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg5)
    lambda.resultg6 <- pgls(X14.CHR ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg6)
    lambda.resultg7 <- pgls(X15.UV ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg7)
    lambda.resultg8 <- pgls(X16.GC ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg8)
    lambda.resultg9 <- pgls(X17.DIST ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg9)
    lambda.resultg10 <- pgls(X3.MSUG ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg10)
    lambda.resultg11 <- pgls(X4.CSUG ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg11)
    
    
    lambda.resulth1 <- pgls(X9.SIZ ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth1)
    lambda.resulth0 <- pgls(Floral.display ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth0)
    lambda.resulth0.0 <- pgls(FdSize ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth0.0)
    lambda.resulth2 <- pgls(X5.NPOL ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth2)
    lambda.resulth3 <- pgls(X6.VPOL ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth3)
    lambda.resulth4 <- pgls(X12.HUE ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth4)
    lambda.resulth5 <- pgls(X13.BRI ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth5)
    lambda.resulth6 <- pgls(X14.CHR ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth6)
    lambda.resulth7 <- pgls(X15.UV ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth7)
    lambda.resulth8 <- pgls(X16.GC ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth8)
    lambda.resulth9 <- pgls(X17.DIST ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth9)
    lambda.resulth10 <- pgls(X3.MSUG ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth10)
    lambda.resulth11 <- pgls(X4.CSUG ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth11)

    head(mydata)
    
    lambda.resulti1 <- pgls(X9.SIZ ~ X19.COLOR,color, lambda = "ML")
    summary(lambda.resulti1)
    lambda.resulth2 <- pgls(X5.NPOL ~ X19.COLOR, color, lambda = "ML")
    summary(lambda.resulth2)
    lambda.resulth3 <- pgls(X6.VPOL ~ X19.COLOR, color, lambda = "ML")
    summary(lambda.resulth3)
    lambda.resulth4 <- pgls(X12.HUE ~ X19.COLOR, color, lambda = "ML")
    summary(lambda.resulth4)
    lambda.resulth5 <- pgls(X13.BRI ~ X19.COLOR, color, lambda = "ML")
    summary(lambda.resulth5)
    lambda.resulth6 <- pgls(X14.CHR ~ X19.COLOR, color, lambda = "ML")
    summary(lambda.resulth6)
    lambda.resulth7 <- pgls(X15.UV ~ X19.COLOR, color, lambda = "ML")
    summary(lambda.resulth7)
    lambda.resulth8 <- pgls(X16.GC ~ X19.COLOR, color, lambda = "ML")
    summary(lambda.resulth8)
    lambda.resulth9 <- pgls(X17.DIST ~ X19.COLOR, color, lambda = "ML")
    summary(lambda.resulth9)
    lambda.resulth10 <- pgls(X3.MSUG ~ X19.COLOR, color, lambda = "ML")
    summary(lambda.resulth10)
    lambda.resulth11 <- pgls(X4.CSUG ~ X19.COLOR, color, lambda = "ML")
    summary(lambda.resulth11)
    lambda.resulth0 <- pgls(Floral.display ~ X19.COLOR, color, lambda = "ML")
    summary(lambda.resulth0)
    lambda.resulth0.0 <- pgls(FdSize ~ X19.COLOR, color, lambda = "ML")
    summary(lambda.resulth0.0)
    

       lambda.resulth1 <- pgls(X9.SIZ ~  X20.COROLA,color, lambda = "ML")
    summary(lambda.resulth1)
    lambda.resulth0 <- pgls(Floral.display ~  X20.COROLA,color, lambda = "ML")
    summary(lambda.resulth0)
    lambda.resulth0.0 <- pgls(FdSize ~  X20.COROLA,color, lambda = "ML")
    summary(lambda.resulth0.0)
    lambda.resulth2 <- pgls(X5.NPOL ~ X20.COROLA, color, lambda = "ML")
    summary(lambda.resulth2)
    lambda.resulth3 <- pgls(X6.VPOL ~ X20.COROLA, color, lambda = "ML")
    summary(lambda.resulth3)
    lambda.resulth4 <- pgls(X12.HUE ~ X20.COROLA, color, lambda = "ML")
    summary(lambda.resulth4)
    lambda.resulth5 <- pgls(X13.BRI ~ X20.COROLA, color, lambda = "ML")
    summary(lambda.resulth5)
    lambda.resulth6 <- pgls(X14.CHR ~ X20.COROLA, color, lambda = "ML")
    summary(lambda.resulth6)
    lambda.resulth7 <- pgls(X15.UV ~ X20.COROLA, color, lambda = "ML")
    summary(lambda.resulth7)
    lambda.resulth8 <- pgls(X16.GC ~ X20.COROLA, color, lambda = "ML")
    summary(lambda.resulth8)
    lambda.resulth9 <- pgls(X17.DIST ~ X20.COROLA, color, lambda = "ML")
    summary(lambda.resulth9)
    lambda.resulth10 <- pgls(X3.MSUG ~ X20.COROLA, color, lambda = "ML")
    summary(lambda.resulth10)
    lambda.resulth11 <- pgls(X4.CSUG ~ X20.COROLA, color, lambda = "ML")
    summary(lambda.resulth11)
    
    
    
    
    
     lambda.resultp1 <- pgls(X9.SIZ ~ X21.NECTAR, color, lambda = "ML")
    summary(lambda.resultp1)
    anova(lambda.resultp1)
    lambda.resultp0 <- pgls(Floral.display ~ X21.NECTAR, color, lambda = "ML")
    summary(lambda.resultp0)
    lambda.resultp0.0 <- pgls(FdSize ~ X21.NECTAR, color, lambda = "ML")
    summary(lambda.resultp0.0)
    
    lambda.resultp2 <- pgls(X5.NPOL ~ X21.NECTAR, color, lambda = "ML")
    summary(lambda.resultp2)
    lambda.resultp3 <- pgls(X6.VPOL ~ X21.NECTAR, color, lambda = "ML")
    summary(lambda.resultp3)
    lambda.resultp4 <- pgls(X12.HUE ~ X21.NECTAR, color, lambda = "ML")
    summary(lambda.resultp4)
    lambda.resultp5 <- pgls(X13.BRI ~ X21.NECTAR, color, lambda = "ML")
    summary(lambda.resultp5)
    lambda.resultp6 <- pgls(X14.CHR ~ X21.NECTAR, color, lambda = "ML")
    summary(lambda.resultp6)
    lambda.resultp7 <- pgls(X15.UV ~ X21.NECTAR, color, lambda = "ML")
    summary(lambda.resultp7)
    lambda.resultp8 <- pgls(X16.GC ~ X21.NECTAR, color, lambda = "ML")
    summary(lambda.resultp8)
    lambda.resultp9 <- pgls(X17.DIST ~ X21.NECTAR, color, lambda = "ML")
    summary(lambda.resultp9)

    
    
#MULVARIABLES MODELS


lambda.result1.multi <- pgls(X6.VPOL ~ X9.SIZ + X16.GC + X17.DIST + X13.BRI + X14.CHR, color, lambda = "ML")
    summary(lambda.result1.multi)
    
    lambda.result2.multi <- pgls(X5.NPOL ~ X9.SIZ  + X16.GC + X17.DIST + X13.BRI  + X14.CHR, color, lambda = "ML")
    summary(lambda.result2.multi)
    
    lambda.result3.multi <- pgls(X3.MSUG ~ X9.SIZ  + X16.GC + X17.DIST + X13.BRI + X14.CHR, color, lambda = "ML")
    summary(lambda.result3.multi)
    
    lambda.result4.multi <- pgls(X4.CSUG ~ X9.SIZ  + X16.GC + X17.DIST + X13.BRI  + X14.CHR, color, lambda = "ML")
    summary(lambda.result4.multi)

    lambda.result5.multi <- pgls(X4.CSUG ~ X9.SIZ  + X16.GC + X17.DIST, color, lambda = "ML")
    summary(lambda.result5.multi)
    
    lambda.result6.multi <- pgls(X4.CSUG ~ X16.GC + X17.DIST, color, lambda = "ML")
    summary(lambda.result6.multi)

```

Phylogenetic signal of cathegorical variables

```{r, echo = F}


resulti1 <- phylo.d(mydata, mytree2, X2.Especies2, X10.SIM, permut = 1000, rnd.bias=NULL)
summary(resulti1)

###This is a method I have found to calculate phylogenetic signal for more than two categories
library(geiger)
hexagon <- mydata$X18.CAT
names(hexagon) <- mydata$X2.Especies2
mytree3 <- multi2di(mytree2)
resulti1 <- fitDiscrete(mytree3, hexagon, model = "ER", transform = "lambda", niter = 100, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
resulti1

library(geiger)
symmetry <- mydata$X10.SIM
names(symmetry) <- mydata$X2.Especies2
mytree3 <- multi2di(mytree2)
resultim <- fitDiscrete(mytree3, symmetry, model = "ER", transform = "lambda", niter = 100, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
resultim

library(geiger)
symmetry <- mydata$X10.SIM
names(symmetry) <- mydata$X2.Especies2
mytree3 <- multi2di(mytree2)
resultim <- fitDiscrete(mytree3, symmetry, model = "ER", transform = "lambda", niter = 100, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
resultim

library(geiger)
NECTAR <- mydata$X21.NECTAR
names(NECTAR) <- mydata$X2.Especies2
mytree3 <- multi2di(mytree2)
resultin <- fitDiscrete(mytree3, NECTAR, model = "ER", transform = "lambda", niter = 100, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
resultin





```



plot!

```{r}
library(phytools)


#MSUG
dat.MSUG <- mydata$X3.MSUG
names(dat.MSUG) <- mydata$X2.Especies2
names(dat.MSUG)[is.na(dat.MSUG) == TRUE]
tree <- drop.tip(mytree2, names(dat.MSUG)[is.na(dat.MSUG) == TRUE])
dat.MSUG <- dat.MSUG[is.na(dat.MSUG) == FALSE]

contMap.MSUG <-contMap(tree,dat.MSUG,plot=FALSE)
plot(contMap.MSUG,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))


#CSUG
dat.CSUG <- mydata$X4.CSUG
names(dat.CSUG) <- mydata$X2.Especies2
names(dat.CSUG)[is.na(dat.CSUG) == TRUE]
tree <- drop.tip(mytree2, names(dat.CSUG)[is.na(dat.CSUG) == TRUE])
dat.CSUG <- dat.CSUG[is.na(dat.CSUG) == FALSE]

contMap.CSUG <-contMap(tree,dat.CSUG,plot=FALSE)
plot(contMap.CSUG,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))



#NPOL
dat.NPOL <- mydata$X5.NPOL
names(dat.NPOL) <- mydata$X2.Especies2
names(dat.NPOL)[is.na(dat.NPOL) == TRUE]
tree <- drop.tip(mytree2, names(dat.NPOL)[is.na(dat.NPOL) == TRUE])
dat.NPOL <- dat.NPOL[is.na(dat.NPOL) == FALSE]

contMap.NPOL <-contMap(tree,dat.NPOL,plot=FALSE)
plot(contMap.NPOL,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))


#VPOL
dat.VPOL <- mydata$X6.VPOL
names(dat.VPOL) <- mydata$X2.Especies2
names(dat.VPOL)[is.na(dat.VPOL) == TRUE]
tree <- drop.tip(mytree2, names(dat.VPOL)[is.na(dat.VPOL) == TRUE])
dat.VPOL <- dat.VPOL[is.na(dat.VPOL) == FALSE]

contMap.VPOL <-contMap(tree,dat.VPOL,plot=FALSE)
plot(contMap.VPOL,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#SIZ
dat.SIZ <- mydata$X9.SIZ
names(dat.SIZ) <- mydata$X2.Especies2
names(dat.SIZ)[is.na(dat.SIZ) == TRUE]
tree <- drop.tip(mytree2, names(dat.SIZ)[is.na(dat.SIZ) == TRUE])
dat.SIZ <- dat.SIZ[is.na(dat.SIZ) == FALSE]

contMap.SIZ <-contMap(tree,dat.SIZ,plot=FALSE)
plot(contMap.SIZ,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#HUE
dat.HUE <- mydata$X12.HUE
names(dat.HUE) <- mydata$X2.Especies2
names(dat.HUE)[is.na(dat.HUE) == TRUE]
tree <- drop.tip(mytree2, names(dat.HUE)[is.na(dat.HUE) == TRUE])
dat.HUE <- dat.HUE[is.na(dat.HUE) == FALSE]

contMap.HUE <-contMap(tree,dat.HUE,plot=FALSE)
plot(contMap.HUE,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#BRI
dat.BRI <- mydata$X13.BRI
names(dat.BRI) <- mydata$X2.Especies2
names(dat.BRI)[is.na(dat.BRI) == TRUE]
tree <- drop.tip(mytree2, names(dat.BRI)[is.na(dat.BRI) == TRUE])
dat.BRI <- dat.BRI[is.na(dat.BRI) == FALSE]

contMap.BRI <-contMap(tree,dat.BRI,plot=FALSE)
plot(contMap.BRI,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#CHR
dat.CHR <- mydata$X14.CHR
names(dat.CHR) <- mydata$X2.Especies2
names(dat.CHR)[is.na(dat.CHR) == TRUE]
tree <- drop.tip(mytree2, names(dat.CHR)[is.na(dat.CHR) == TRUE])
dat.CHR <- dat.CHR[is.na(dat.CHR) == FALSE]

contMap.CHR <-contMap(tree,dat.CHR,plot=FALSE)
plot(contMap.CHR,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#UV
dat.UV <- mydata$X15.UV
names(dat.UV) <- mydata$X2.Especies2
names(dat.UV)[is.na(dat.UV) == TRUE]
tree <- drop.tip(mytree2, names(dat.UV)[is.na(dat.UV) == TRUE])
dat.UV <- dat.UV[is.na(dat.UV) == FALSE]

contMap.UV <-contMap(tree,dat.UV,plot=FALSE)
plot(contMap.UV,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#GC
dat.GC <- mydata$X16.GC
names(dat.GC) <- mydata$X2.Especies2
names(dat.GC)[is.na(dat.GC) == TRUE]
tree <- drop.tip(mytree2, names(dat.GC)[is.na(dat.GC) == TRUE])
dat.GC <- dat.GC[is.na(dat.GC) == FALSE]

contMap.GC <-contMap(tree,dat.GC,plot=FALSE)
plot(contMap.GC,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#DIST
dat.DIST <- mydata$X17.DIST
names(dat.DIST) <- mydata$X2.Especies2
names(dat.DIST)[is.na(dat.DIST) == TRUE]
tree <- drop.tip(mytree2, names(dat.DIST)[is.na(dat.DIST) == TRUE])
dat.DIST <- dat.DIST[is.na(dat.DIST) == FALSE]

contMap.DIST <-contMap(tree,dat.DIST,plot=FALSE)
plot(contMap.DIST,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#Floral.display
dat.Fd <- mydata$Floral.display
names(dat.Fd) <- mydata$X2.Especies2
names(dat.Fd)[is.na(dat.Fd) == TRUE]
tree <- drop.tip(mytree2, names(dat.Fd)[is.na(dat.Fd) == TRUE])
dat.Fd <- dat.Fd[is.na(dat.Fd) == FALSE]

contMap.Fd <-contMap(tree,dat.Fd,plot=FALSE)
plot(contMap.Fd,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))


#Floral.display x Size
dat.FdSize <- mydata$FdSize
names(dat.FdSize) <- mydata$X2.Especies2
names(dat.FdSize)[is.na(dat.FdSize) == TRUE]
tree <- drop.tip(mytree2, names(dat.FdSize)[is.na(dat.FdSize) == TRUE])
dat.FdSize <- dat.FdSize[is.na(dat.FdSize) == FALSE]

contMap.FdSize <-contMap(tree,dat.FdSize,plot=FALSE)
plot(contMap.FdSize,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))



```

