---
title: "Color y recompensas"
author: "Marcial"
date: "01/09/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
1. Install and load packages

```{r, echo = F}
#devtools::install_github("jinyizju/V.PhyloMaker")
library(V.PhyloMaker)


```


3. Frequency matrix.

```{r, echo = F}
mydata <- read.csv("mydata3.csv", sep = ",", header=TRUE, stringsAsFactors=FALSE, fileEncoding="latin1")
mydata

```



3. Create your tree and plot

```{r, echo = F}

genera<-sapply(strsplit(mydata[,2]," "),function(x) x[1])

data <- data.frame(species = mydata[,2], genus = genera, family = mydata[,1])
my.phylo.maker <- phylo.maker(data, tree = GBOTB.extended, nodes = nodes.info.1, output.sp.list = TRUE, output.tree = FALSE, scenarios = c("S1","S2","S3"), r = 1)

plot(my.phylo.maker$scenario.3, cex = 0.6)

write.tree(my.phylo.maker$scenario.3, file = "mytree.tree")



```




```{r, echo = F}
library(caper)

mytree2 <- read.tree(file="mytree.tree")

class(mytree2)
plot(mytree2)
mydata$X5.NPOL <- as.numeric(mydata$X5.NPOL)
color <- comparative.data(mytree2, mydata, X2.Especies2, vcv=TRUE, vcv.dim=2, na.omit=F, 
	             force.root=FALSE, warn.dropped=T, scope=NULL)
plot(color$phy)
color$phy
color$dropped
dim(color$vcv)
    lambda.result1 <- pgls(X3.MSUG ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.result1)
    lambda.result2 <- pgls(X3.MSUG ~ X6.VPOL, color, lambda = "ML")
    summary(lambda.result2)
    lambda.result3 <- pgls(X3.MSUG ~ X9.SIZ, color, lambda = "ML")
    summary(lambda.result3)
    lambda.result4 <- pgls(X3.MSUG ~ X12.HUE, color, lambda = "ML")
    summary(lambda.result4)
    lambda.result5 <- pgls(X3.MSUG ~ X13.BRI, color, lambda = "ML")
    summary(lambda.result5)
    lambda.result6 <- pgls(X3.MSUG ~ X14.CHR, color, lambda = "ML")
    summary(lambda.result6)
    lambda.result7 <- pgls(X3.MSUG ~ X15.UV, color, lambda = "ML")
    summary(lambda.result7)
    lambda.result8 <- pgls(X3.MSUG ~ X16.GC, color, lambda = "ML")
    summary(lambda.result8)
    lambda.result9 <- pgls(X3.MSUG ~ X17.DIST, color, lambda = "ML")
    summary(lambda.result9)
    
    lambda.resultb1 <- pgls(X4.CSUG ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.resultb1)
    lambda.resultb2 <- pgls(X4.CSUG ~ X6.VPOL, color, lambda = "ML")
    summary(lambda.resultb2)
    lambda.resultb3 <- pgls(X4.CSUG ~ X9.SIZ, color, lambda = "ML")
    summary(lambda.resultb3)
    lambda.resultb4 <- pgls(X4.CSUG ~ X12.HUE, color, lambda = "ML")
    summary(lambda.resultb4)
    lambda.resultb5 <- pgls(X4.CSUG ~ X13.BRI, color, lambda = "ML")
    summary(lambda.resultb5)
    lambda.resultb6 <- pgls(X4.CSUG ~ X14.CHR, color, lambda = "ML")
    summary(lambda.resultb6)
    lambda.resultb7 <- pgls(X4.CSUG ~ X15.UV, color, lambda = "ML")
    summary(lambda.resultb7)
    lambda.resultb8 <- pgls(X4.CSUG ~ X16.GC, color, lambda = "ML")
    summary(lambda.resultb8)
    lambda.resultb9 <- pgls(X4.CSUG ~ X17.DIST, color, lambda = "ML")
    summary(lambda.resultb9)

    lambda.resultc1 <- pgls(X5.NPOL ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resultc1)
    lambda.resultc2 <- pgls(X5.NPOL ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resultc2)
    lambda.resultc3 <- pgls(X5.NPOL ~ X9.SIZ, color, lambda = "ML")
    summary(lambda.resultc3)
    lambda.resultc4 <- pgls(X5.NPOL ~ X12.HUE, color, lambda = "ML")
    summary(lambda.resultc4)
    lambda.resultc5 <- pgls(X5.NPOL ~ X13.BRI, color, lambda = "ML")
    summary(lambda.resultc5)
    lambda.resultc6 <- pgls(X5.NPOL ~ X14.CHR, color, lambda = "ML")
    summary(lambda.resultc6)
    lambda.resultc7 <- pgls(X5.NPOL ~ X15.UV, color, lambda = "ML")
    summary(lambda.resultc7)
    lambda.resultc8 <- pgls(X5.NPOL ~ X16.GC, color, lambda = "ML")
    summary(lambda.resultc8)
    lambda.resultc9 <- pgls(X5.NPOL ~ X17.DIST, color, lambda = "ML")
    summary(lambda.resultc9)
    
    
    lambda.resultd1 <- pgls(X6.VPOL ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resultd1)
    lambda.resultd2 <- pgls(X6.VPOL ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resultd2)
    lambda.resultd3 <- pgls(X6.VPOL ~ X9.SIZ, color, lambda = "ML")
    summary(lambda.resultd3)
    lambda.resultd4 <- pgls(X6.VPOL ~ X12.HUE, color, lambda = "ML")
    summary(lambda.resultd4)
    lambda.resultd5 <- pgls(X6.VPOL ~ X13.BRI, color, lambda = "ML")
    summary(lambda.resultd5)
    lambda.resultd6 <- pgls(X6.VPOL ~ X14.CHR, color, lambda = "ML")
    summary(lambda.resultd6)
    lambda.resultd7 <- pgls(X6.VPOL ~ X15.UV, color, lambda = "ML")
    summary(lambda.resultd7)
    lambda.resultd8 <- pgls(X6.VPOL ~ X16.GC, color, lambda = "ML")
    summary(lambda.resultd8)
    lambda.resultd9 <- pgls(X6.VPOL ~ X17.DIST, color, lambda = "ML")
    summary(lambda.resultd9)

    
    lambda.resulte1 <- pgls(X9.SIZ ~ X3.MSUG, color, lambda = "ML")
    summary(lambda.resulte1)
    lambda.resulte2 <- pgls(X9.SIZ ~ X4.CSUG, color, lambda = "ML")
    summary(lambda.resulte2)
    lambda.resulte3 <- pgls(X9.SIZ ~ X5.NPOL, color, lambda = "ML")
    summary(lambda.resulte3)
    lambda.resulte4 <- pgls(X9.SIZ ~ X6.VPOL, color, lambda = "ML")
    summary(lambda.resulte4)
    lambda.resulte5 <- pgls(X9.SIZ ~ X12.HUE, color, lambda = "ML")
    summary(lambda.resulte5)
    lambda.resulte6 <- pgls(X9.SIZ ~ X13.BRI, color, lambda = "ML")
    summary(lambda.resulte6)
    lambda.resulte7 <- pgls(X9.SIZ ~ X14.CHR, color, lambda = "ML")
    summary(lambda.resulte7)
    lambda.resulte8 <- pgls(X9.SIZ ~ X15.UV, color, lambda = "ML")
    summary(lambda.resulte8)
    lambda.resulte9 <- pgls(X9.SIZ ~ X16.GC, color, lambda = "ML")
    summary(lambda.resulte9)
    lambda.resulte10 <- pgls(X9.SIZ ~ X17.DIST, color, lambda = "ML")
    summary(lambda.resulte10)

```



Phylogenetic signal

```{r, echo = F}

lambda.resultf1 <- pgls(X3.MSUG ~ 1, color, lambda = "ML")
    summary(lambda.resultf1)
lambda.resultf2 <- pgls(X4.CSUG ~ 1, color, lambda = "ML")
    summary(lambda.resultf2)
lambda.resultf3 <- pgls(X5.NPOL ~ 1, color, lambda = "ML")
    summary(lambda.resultf3)
lambda.resultf4 <- pgls(X6.VPOL ~ 1, color, lambda = "ML")
    summary(lambda.resultf4)
lambda.resultf5 <- pgls(X9.SIZ ~ 1, color, lambda = "ML")
    summary(lambda.resultf5)
lambda.resultf6 <- pgls(X12.HUE ~ 1, color, lambda = "ML")
    summary(lambda.resultf6)
lambda.resultf7 <- pgls(X13.BRI ~ 1, color, lambda = "ML")
    summary(lambda.resultf7)
lambda.resultf8 <- pgls(X14.CHR ~ 1, color, lambda = "ML")
    summary(lambda.resultf8)
lambda.resultf9 <- pgls(X15.UV ~ 1, color, lambda = "ML")
    summary(lambda.resultf9)
lambda.resultf10 <- pgls(X16.GC ~ 1, color, lambda = "ML")
    summary(lambda.resultf10)
lambda.resultf11 <- pgls(X17.DIST ~ 1, color, lambda = "ML")
    summary(lambda.resultf11)
    
    
    


    
```

Plotting

```{r, echo = F}

#library(devtools)
#install_github("liamrevell/phytools")
library(phytools)

rownames(mydata) <- as.character(mydata$X2.Especies2)
colors<-colorRampPalette(colors=gray.colors(100, alpha = 1))(100)
traits <- mydata[,c("X3.MSUG", "X4.CSUG", "X5.NPOL", "X6.VPOL", "X9.SIZ", "X12.HUE", "X13.BRI", "X14.CHR", "X15.UV", "X16.GC", "X17.DIST")]
colnames(traits) <- c("Sugar Mass", "Sugar Conc.", "Pollen Num.", "Pollen Vol.", "Flow. Size", "HUE", "BRI", "CHR", "UV", "GC", "DIST")
phylo.heatmap(mytree2,traits,ftype="i", fsize = c(0.35,0.5,0.5),colors=colors,standardize=T,lwd=1, pts=F, grid=F, legend = T, split=c(0.50,0.50))


```

Cathegorical variables

```{r,  echo = F}

    lambda.resultg1 <- pgls(X9.SIZ ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg1)
    anova(lambda.resultg1)
    lambda.resultg2 <- pgls(X5.NPOL ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg2)
    lambda.resultg3 <- pgls(X6.VPOL ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg3)
    lambda.resultg4 <- pgls(X12.HUE ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg4)
    lambda.resultg5 <- pgls(X13.BRI ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg5)
    lambda.resultg6 <- pgls(X14.CHR ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg6)
    lambda.resultg7 <- pgls(X15.UV ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg7)
    lambda.resultg8 <- pgls(X16.GC ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg8)
    lambda.resultg9 <- pgls(X17.DIST ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg9)
    lambda.resultg10 <- pgls(X3.MSUG ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg10)
    lambda.resultg11 <- pgls(X4.CSUG ~ X10.SIM, color, lambda = "ML")
    summary(lambda.resultg11)
    
    
    lambda.resulth1 <- pgls(X9.SIZ ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth1)
    lambda.resulth2 <- pgls(X5.NPOL ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth2)
    lambda.resulth3 <- pgls(X6.VPOL ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth3)
    lambda.resulth4 <- pgls(X12.HUE ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth4)
    lambda.resulth5 <- pgls(X13.BRI ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth5)
    lambda.resulth6 <- pgls(X14.CHR ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth6)
    lambda.resulth7 <- pgls(X15.UV ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth7)
    lambda.resulth8 <- pgls(X16.GC ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth8)
    lambda.resulth9 <- pgls(X17.DIST ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth9)
    lambda.resulth10 <- pgls(X3.MSUG ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth10)
    lambda.resulth11 <- pgls(X4.CSUG ~ X18.CAT, color, lambda = "ML")
    summary(lambda.resulth11)

    

```

Phylogenetic signal of cathegorical variables

```{r, echo = F}


resulti1 <- phylo.d(mydata, mytree2, X2.Especies2, X10.SIM, permut = 1000, rnd.bias=NULL)
summary(resulti1)

###This is a method I have found to calculate phylogenetic signal for more than two categories
library(geiger)
hexagon <- mydata$X18.CAT
names(hexagon) <- mydata$X2.Especies2
mytree3 <- multi2di(mytree2)
resulti1 <- fitDiscrete(mytree3, hexagon, model = "ER", transform = "lambda", niter = 100, FAIL = 1e+200, hessian = FALSE, CI = 0.95, ncores=NULL)
resulti1


```



plot!

```{r}
library(phytools)


#MSUG
dat.MSUG <- mydata$X3.MSUG
names(dat.MSUG) <- mydata$X2.Especies2
names(dat.MSUG)[is.na(dat.MSUG) == TRUE]
tree <- drop.tip(mytree2, names(dat.MSUG)[is.na(dat.MSUG) == TRUE])
dat.MSUG <- dat.MSUG[is.na(dat.MSUG) == FALSE]

contMap.MSUG <-contMap(tree,dat.MSUG,plot=FALSE)
plot(contMap.MSUG,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))


#CSUG
dat.CSUG <- mydata$X4.CSUG
names(dat.CSUG) <- mydata$X2.Especies2
names(dat.CSUG)[is.na(dat.CSUG) == TRUE]
tree <- drop.tip(mytree2, names(dat.CSUG)[is.na(dat.CSUG) == TRUE])
dat.CSUG <- dat.CSUG[is.na(dat.CSUG) == FALSE]

contMap.CSUG <-contMap(tree,dat.CSUG,plot=FALSE)
plot(contMap.CSUG,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))



#NPOL
dat.NPOL <- mydata$X5.NPOL
names(dat.NPOL) <- mydata$X2.Especies2
names(dat.NPOL)[is.na(dat.NPOL) == TRUE]
tree <- drop.tip(mytree2, names(dat.NPOL)[is.na(dat.NPOL) == TRUE])
dat.NPOL <- dat.NPOL[is.na(dat.NPOL) == FALSE]

contMap.NPOL <-contMap(tree,dat.NPOL,plot=FALSE)
plot(contMap.NPOL,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))


#VPOL
dat.VPOL <- mydata$X6.VPOL
names(dat.VPOL) <- mydata$X2.Especies2
names(dat.VPOL)[is.na(dat.VPOL) == TRUE]
tree <- drop.tip(mytree2, names(dat.VPOL)[is.na(dat.VPOL) == TRUE])
dat.VPOL <- dat.VPOL[is.na(dat.VPOL) == FALSE]

contMap.VPOL <-contMap(tree,dat.VPOL,plot=FALSE)
plot(contMap.VPOL,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#SIZ
dat.SIZ <- mydata$X9.SIZ
names(dat.SIZ) <- mydata$X2.Especies2
names(dat.SIZ)[is.na(dat.SIZ) == TRUE]
tree <- drop.tip(mytree2, names(dat.SIZ)[is.na(dat.SIZ) == TRUE])
dat.SIZ <- dat.SIZ[is.na(dat.SIZ) == FALSE]

contMap.SIZ <-contMap(tree,dat.SIZ,plot=FALSE)
plot(contMap.SIZ,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#HUE
dat.HUE <- mydata$X12.HUE
names(dat.HUE) <- mydata$X2.Especies2
names(dat.HUE)[is.na(dat.HUE) == TRUE]
tree <- drop.tip(mytree2, names(dat.HUE)[is.na(dat.HUE) == TRUE])
dat.HUE <- dat.HUE[is.na(dat.HUE) == FALSE]

contMap.HUE <-contMap(tree,dat.HUE,plot=FALSE)
plot(contMap.HUE,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#BRI
dat.BRI <- mydata$X13.BRI
names(dat.BRI) <- mydata$X2.Especies2
names(dat.BRI)[is.na(dat.BRI) == TRUE]
tree <- drop.tip(mytree2, names(dat.BRI)[is.na(dat.BRI) == TRUE])
dat.BRI <- dat.BRI[is.na(dat.BRI) == FALSE]

contMap.BRI <-contMap(tree,dat.BRI,plot=FALSE)
plot(contMap.BRI,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#CHR
dat.CHR <- mydata$X14.CHR
names(dat.CHR) <- mydata$X2.Especies2
names(dat.CHR)[is.na(dat.CHR) == TRUE]
tree <- drop.tip(mytree2, names(dat.CHR)[is.na(dat.CHR) == TRUE])
dat.CHR <- dat.CHR[is.na(dat.CHR) == FALSE]

contMap.CHR <-contMap(tree,dat.CHR,plot=FALSE)
plot(contMap.CHR,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#UV
dat.UV <- mydata$X15.UV
names(dat.UV) <- mydata$X2.Especies2
names(dat.UV)[is.na(dat.UV) == TRUE]
tree <- drop.tip(mytree2, names(dat.UV)[is.na(dat.UV) == TRUE])
dat.UV <- dat.UV[is.na(dat.UV) == FALSE]

contMap.UV <-contMap(tree,dat.UV,plot=FALSE)
plot(contMap.UV,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#GC
dat.GC <- mydata$X16.GC
names(dat.GC) <- mydata$X2.Especies2
names(dat.GC)[is.na(dat.GC) == TRUE]
tree <- drop.tip(mytree2, names(dat.GC)[is.na(dat.GC) == TRUE])
dat.GC <- dat.GC[is.na(dat.GC) == FALSE]

contMap.GC <-contMap(tree,dat.GC,plot=FALSE)
plot(contMap.GC,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))

#DIST
dat.DIST <- mydata$X17.DIST
names(dat.DIST) <- mydata$X2.Especies2
names(dat.DIST)[is.na(dat.DIST) == TRUE]
tree <- drop.tip(mytree2, names(dat.DIST)[is.na(dat.DIST) == TRUE])
dat.DIST <- dat.DIST[is.na(dat.DIST) == FALSE]

contMap.DIST <-contMap(tree,dat.DIST,plot=FALSE)
plot(contMap.DIST,type="fan",legend=0.7*max(nodeHeights(tree)),
    sig=2,fsize=c(0.7,0.9))
```

